Add environment variable check in Docker build workflow
Added a check for required environment variables before building the Docker image.

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -31,6 +31,13 @@ jobs:
         run: |
           gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
 
+      - name: Check required environment variables
+        run: |
+          if [ -z "${{ env.PROJECT_ID }}" ] || [ -z "${{ env.REGION }}" ] || [ -z "${{ env.REPOSITORY }}" ]; then
+              echo "One or more required environment variables (PROJECT_ID, REGION, REPOSITORY) are missing."
+              exit 1
+            fi
+
       - name: Build Docker image
         run: |
           docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" .
